title: Sohee (Sophia) Park 
#logo: 
description: Driven by the power of data to foster social and global change, I am an analytics professional with expertise in transforming data into actionable insights and effective strategies. My focus is on bridging the gap between technical analysis and real-world business impact, while cultivating an inclusive and diverse learning community.
theme: jekyll-theme-minimal 
